### PR TITLE
Ruby version update + Docker support

### PR DESCRIPTION
**Pull request by suz-stripe**
👋 Hello! Some proposed updates for this app are in this PR.

1. I updated the recommended Ruby to the latest stable version.
2. Expanded the README with a little more explanation and organisation
3. I added a Dockerfile 🐳 which will be used for the pending Docker image repo on Docker Hub. This is a convenient option to run this app for folks with Docker installed locally on their machines and if they're comfy running containers.

I used [Alpine](https://alpinelinux.org/) for the linux base in the container. Ruby 2.6.5 Alpine Docker compressed image build size: ~25MB which should pull down ok even on a slowish internet connection.

Marked as draft because it's not ready for merge until the Docker repo is approved and set up.

### CODE REVIEW

**Comment by suz-stripe** [comment]
🙋 this is now ready for review as the Docker repo is now created. If this PR is approved I will then:
1. tag the Docker images based on the HEAD sha
2. push the image to Docker
3. manually test pulling to my machine to ensure everything checks out
4. merge this PR

**Comment by jil-stripe** [comment]
LGTM! Thanks so much!

Also noticed you updated the ruby version. We had a Jira out for that -- if I assign it to you, would you want to mark it as done?

**Comment by suz-stripe** [comment]
[Container is now hosted](https://hub.docker.com/repository/docker/stripe/example-terminal-backend/general)! 🐋 ☁️ 

Manually tested and working as expected with the [js demo app](https://stripe-terminal-demo.appspot.com/), so I'm merging this and closing it out 🎉 

Thanks for the review @jil-stripe

**Comment by jil-stripe** [comment]
woot!

**Pull request merged**
